{
 "title": "Pizza Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "HTTP Req/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by(source) (rate(http_requests_total{source=\"jwt-pizza-service-dev\"}[1m]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "user_count_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "endpoint latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "endpointLatency_milliseconds_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "avg by(source) (endpointLatency_milliseconds_total{source=\"jwt-pizza-service\", endpoint!=\"UnknownEndpoint\"})",
     "legendFormat": "Average (valid endpoints)"
    }
   ]
  },
  {
   "title": "Authentications/Authorizations and (see desc)",
   "type": "timeseries",
   "description": "all 'api/auth' failures and 401,403 errors for any api endpoints requiring auth (such as adding menu item)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "auth_checks_total{source=\"jwt-pizza-service\", passesAuth=\"true\"}",
     "legendFormat": "success"
    },
    {
     "expr": "auth_checks_total{source=\"jwt-pizza-service\", passesAuth=\"false\"}",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "revenue_bitcoin_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid Endpoint Requests / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "rate(invalid_endpoints_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Pizza Purchases / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(orders_total{source=\"jwt-pizza-service\", success=\"true\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(orders_total{source=\"jwt-pizza-service\", success=\"false\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "order latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "orderLatency_milliseconds_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}